name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12.16
    
    - name: Save key
      env:
        ACCESS_KEY: ${{ secrets.OPS_KEY_ENC }}
      run: |
        echo "$ACCESS_KEY" | base64 -d > $HOME/KEY
        chmod 400 $HOME/KEY

    - name: Install dependencies
      run: yarn install
    
    - name: Build
      run: yarn build
    
    - name: Deploy to server
      run: |
        scp -r -i "$HOME/KEY" -o StrictHostKeyChecking=no ./build ops@url.ojaswa.com:/var/www/url/
        scp -r -i "$HOME/KEY" -o StrictHostKeyChecking=no ./controllers ops@url.ojaswa.com:/var/www/url/
        scp -r -i "$HOME/KEY" -o StrictHostKeyChecking=no ./server.js ops@url.ojaswa.com:/var/www/url/
